version: '3.9'
services:
  flask-api:
    image: devesh121/flask-mongo-api:latest
    container_name: flask-mongo-api
    ports:
      - 5000:5000
    
  mongo-db:
    image: mongo 
    container_name: mongo-container
    ports:
      - 27017:27017

